"""Context assembly — the four §10 layers, to the depth Phase 2 can fill them.

§10 asks for four layers, in this order:

```text
1 System policy      <- prompts/tutor_system.md
2 Student profile    <- Phase 7 (student grade is injected by the policy layer today)
3 Long-term memory   <- Phase 8 (structured conversation summary)
4 Recent conversation <- caller-supplied history, trimmed to memory.recent_turns
```

Layer 1 is followed by the answer-framing prompt (``prompts/solve.md``) and then by
the policy layer's own block, so the most specific instruction is also the last one
the model reads. Layers 2 and 3 are deliberately absent until their phases exist:
this module never fabricates a profile or a "memory" it does not have.

Why the three top blocks become **one** system message
------------------------------------------------------
Qwen3.5's Jinja chat template (the one shipped in the GGUF this project runs)
aborts the request with ``Jinja Exception: System message must be at the beginning``
whenever a system message follows a user/assistant one — verified against the live
llama-server on 2026-09-11 (HTTP 500). Keeping the layers separate is therefore not
portable, so they are concatenated in the documented order inside a single system
message. They remain separate *layers*: each block is still produced by its own
module and the policy block is still generated by :mod:`tutor.tutor.policy`.

No prompt text is embedded here (§13) and no trimming heuristic is hidden: exactly
the last ``memory.recent_turns`` messages survive.
"""

from __future__ import annotations

from collections.abc import Sequence

from tutor.config import MemoryConfig
from tutor.llm.models import ChatMessage
from tutor.llm.prompts import PromptLibrary

SYSTEM_PROMPT = "tutor_system.md"
ANSWER_FRAMING_PROMPT = "solve.md"
LAYER_SEPARATOR = "\n\n"


class ContextBuilder:
    """Turns prompt files + policy instructions + history into chat messages."""

    def __init__(self, prompts: PromptLibrary, config: MemoryConfig) -> None:
        self._prompts = prompts
        self._config = config

    def build(
        self,
        *,
        message: str,
        policy_block: str,
        history: Sequence[ChatMessage] = (),
    ) -> list[ChatMessage]:
        """Assemble the message list for one turn.

        ``history`` must not contain the current ``message``: the caller (Phase 8's
        conversation memory) owns that split.
        """
        layers = [
            self._prompts.get(SYSTEM_PROMPT),
            self._prompts.get(ANSWER_FRAMING_PROMPT),
        ]
        if policy_block.strip():
            layers.append(policy_block)
        messages = [ChatMessage(role="system", content=LAYER_SEPARATOR.join(layers))]
        messages.extend(history[-self._config.recent_turns :])
        messages.append(ChatMessage(role="user", content=message))
        return messages
